### ISSUE TITLE
Error setting up entry to email@xxx.com for hon

### ISSUE THREAD

**Issue by slegars56** [Andre0512/pyhOn#3]
Hi,

When testing your integration I get the following error at the first connection:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/hon/__init__.py", line 32, in async_setup_entry
await hon.setup()
File "/usr/local/lib/python3.10/site-packages/pyhon/api.py", line 57, in setup
device = HonDevice(self, appliance)
File "/usr/local/lib/python3.10/site-packages/pyhon/device.py", line 8, in __init__
appliance["attributes"] = {v["parName"]: v["parValue"] for v in appliance["attributes"]}
KeyError: 'attributes'

Tested on 0.2.1

**Comment by Andre0512** [comment]
Hi, I moved your issue to the right repo. The wine color was a good hint, when added it I had the same issue. I think we can ignore virtual appliances for now. I fixed it and created a new release.
